function showContent(buttonId) {
    var contentContainer = document.getElementById('button-content');
    switch (buttonId) {
        case 'button1':
            contentContainer.innerHTML = "<p class='custom-text-style'>For as long as I can remember, Windows 10 has been an integral part of my digital journey. From the early days of exploring the world of computing to the present, it has been my steadfast companion. As a student, I rely on Windows 10 for my academic pursuits, seamlessly integrating it into my daily routine for school projects and tasks. Its user-friendly interface and compatibility have been instrumental in shaping my digital experiences, making it a reliable platform that has grown with me throughout my educational journey.";
            break;
        case 'button2':
            contentContainer.innerHTML = "<p class='custom-text-style'>As my laptop began to show signs of sluggishness, I sought a solution that would breathe new life into its performance. This quest led me to Ubuntu, an open-source operating system known for its efficiency and resource-friendly nature. Ubuntu's ability to operate with fewer background applications significantly improved my laptop's speed and responsiveness. Beyond its performance benefits, I discovered a world of customization options that allowed me to tailor the system to my preferences. Ubuntu became more than just a solution for speed; it became a canvas for personalization and efficiency, offering a seamless and responsive environment for my computing needs.";
            break;
        case 'button3':
            contentContainer.innerHTML = "<p class='custom-text-style'>My journey with MacOS began during my studies at ROC niveau 2 when faced with the challenge of two broken laptops. Determined to make the most out of the situation, I combined the functional components of both, creating a working laptop that ran on MacOS. Despite the initial hurdles, the system performed admirably, showcasing the resilience of MacOS. While I may not be the biggest fan of its UI, my experience taught me to appreciate the system's functionality. Navigating through MacOS, I discovered its capabilities and developed a proficiency in using it efficiently, making it a valuable part of my technological repertoire.";
            break;
        case 'button4':
            contentContainer.innerHTML = "<p class='custom-text-style'>Driven by a keen interest in cybersecurity, I delved into the realm of ethical hacking and penetration testing. In my quest for a robust toolset, I discovered Kali Linux, a preferred operating system among professional cybersecurity testers. As I began using Kali Linux, its extensive suite of security tools opened up a fascinating world of ethical hacking. The hands-on experience reached a pivotal moment when I successfully tested the security of my own router, realizing the critical importance of strong passwords in maintaining digital security. Kali Linux not only became a powerful ally in my exploration of cybersecurity but also served as a stark reminder of the crucial role cybersecurity plays in our increasingly digital lives.";
            break;
        case 'button5':
            contentContainer.innerHTML = "<p class='custom-text-style'>Faced with performance issues on my school laptop, largely stemming from the burden of numerous background applications on Windows 10, I sought a streamlined alternative. Enter Ghost Spectre, a customized version of Windows 10 designed to eliminate bloatware and unnecessary background processes. Embracing Ghost Spectre, I found a refined and responsive computing experience. Stripped of the excess, it became a go-to solution for a lean and efficient system. The tailored nature of Ghost Spectre not only resolved my laptop's performance woes but also offered a refreshing and enjoyable alternative to the traditional Windows 10 experience.";
            break;  case 'button6':
            contentContainer.innerHTML = "<p class='custom-text-style'>As I ventured into the world of web development for a school project, PhpStorm emerged as my coding companion. Assigned the task of building a flight reservation website, I turned to PhpStorm's sleek interface and robust features. Crafting the site's logic, I ensured that only registered users could unlock the privilege of making flight reservations. PhpStorm's powerful toolkit facilitated smooth coding, turning the complexity of web development into an organized and efficient process. In this digital journey, PhpStorm played a crucial role, helping me transform ideas into a functional website that met the requirements of my school project.";
            break;  case 'button7':
            contentContainer.innerHTML = "<p class='custom-text-style'>When tasked with creating a text-based game for a school project, I decided to inject a bit of fun into the challenge. Opting for creativity, I transformed the assignment into something delightful – a classic Snake game. Python, with its simplicity and versatility, became the ideal language for this endeavor. As the code unfolded, the snake slithered across the terminal, gobbling up pixels and growing longer with each successful 'meal.' The project not only fulfilled the academic requirement but also brought a touch of playfulness to the world of coding. Python, as the backbone of this gaming escapade, proved once again its ability to turn the mundane into the extraordinary.";
            break;  case 'button8':
            contentContainer.innerHTML = "<p class='custom-text-style'>Venturing into the realms of both academia and game development, Visual Studio emerged as my trusted companion. Tasked with learning C# for school projects, I embraced the challenge, navigating the syntax and logic with the assistance of Visual Studio's feature-rich environment. Despite being a beginner, the platform provided a supportive space for honing my coding skills.\n" +
                "\n" +
                "As the journey progressed, I delved into the captivating world of game development using Unity. Visual Studio seamlessly integrated with Unity, becoming the coding cockpit for a small yet exciting VR game project. The lines of code came alive, shaping virtual landscapes and interactive experiences. Through trial and error, Visual Studio stood as a reliable ally, helping me bring my VR game to fruition. In the dynamic intersection of education and game creation, Visual Studio proved to be an invaluable tool, fostering both learning and creativity.";
            break;  case 'button9':
            contentContainer.innerHTML = "<p class='custom-text-style'>While it may not be the flashiest topic, GitHub has been the unsung hero of my coding adventures. In the academic realm, it became the collaborative canvas for group projects, especially when tasked with building websites as a team. The power of version control and seamless collaboration that GitHub offered transformed the sometimes chaotic process of group work into a harmonious symphony of code.\n" +
                "\n" +
                "Beyond the classroom, GitHub extended its influence into the realm of personal projects. Alongside a friend, we embarked on our coding escapade, crafting our own project. GitHub served as the digital sanctuary where our ideas converged, allowing us to share code, track changes, and synchronize our efforts effortlessly.\n" +
                "\n" +
                "Curious minds are always welcome to explore my GitHub repository https://github.com/Delerious28. It might not be the most glamorous showcase, but every commit, pull request, and project tells a story of my coding journey, one line of code at a time.";
            break;  case 'button10':
            contentContainer.innerHTML = "<p class='custom-text-style'>In the vast expanse of game development, Unreal Engine 5 emerged as a tantalizing frontier for my creative aspirations. Eager to delve into the intricacies of game design, I embarked on a journey to master Unreal Engine 5. Armed with online classes and a fervent desire to learn, I envisioned crafting digital worlds and immersive experiences.\n" +
                "\n" +
                "However, the journey faced an unexpected hurdle – my computer's capabilities. Despite the enthusiasm and the wealth of knowledge from online classes, my hardware struggled to keep up with the demands of Unreal Engine 5. The dream of creating in this powerful engine was temporarily put on hold." +
                "\n" +
                "Undeterred, I long for the day when I can return to Unreal Engine 5, armed not just with creative vision but also with the technical prowess to wield its capabilities. Learning C++, the engine's language of choice, is a beacon on the horizon, guiding me towards a future where I can bring my gaming visions to life in the digital realms crafted by Unreal Engine 5.";
            break;
        default:
            contentContainer.innerHTML = "";
    }

    // Show the content container
    contentContainer.style.display = "block";
}
